services:
  redis:
    image: "redis:alpine"
  web:
    build: .
    ports:
      - "8000:8000"
    command: /bin/bash -c "python /code/manage.py migrate --noinput && python /code/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    depends_on:
      - redis
  celery:
    build: .
    command: celery -A config worker -l info --pool=solo
    volumes:
      - .:/code
    depends_on:
      - redis